# -*- coding: utf-8 -*-
"""analisedados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yAhYF5FQYx7iqmh78ijvTchOQnWBdkkf

# Primeiro código do curso
## Subtítulo
"""

print("Hello world!")

